config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :supports
  resources :locations
  resources :partners
  resources :events do
    collection do
      get "search"
    end
  end
  resources :abouts
  resources :static_pages

  root 'static_pages#home'

  get 'board', to: 'abouts#board' 

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: 'Static page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params[:static_page]
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/home.html.erb
  <%= render 'layouts/carousel' %>

  <div class = "">
    <div class "clearfix"></div>
      <div class= "container">
        
  <div class="row">
    <div class = "col-md-9 col-md-offset-2" >    
      <p class= "headline">Our mission is to inspire and enable all young people, especially those who need us most, to reach their full potential </p>
          </div>
        </div>



            <div class="row" style = "margin-left:30px;">

              <div class="col-sm-6 col-md-4">        
                <div class ="overlay">
                  <img src = "http://i304.photobucket.com/albums/nn184/boysandgirlsclubsofthesouthbay/bgcsbkids_zpsx3jd50wk.jpg">
                      <h1>Give</h1> 
                </div>
              </div>


              <div class="col-sm-6 col-md-4">           
                  <div class ="overlay">
                    <img src = "http://i304.photobucket.com/albums/nn184/boysandgirlsclubsofthesouthbay/bgcsbmembers_zpsjkdfbkse.jpg">
                        <h1> Volunteer</h1>
                  </div>
              </div>


              <div class="col-sm-6 col-md-4">       
                  <div class ="overlay">
                    <img src = "http://i304.photobucket.com/albums/nn184/boysandgirlsclubsofthesouthbay/bgcsbsupport_zpsjibijfjb.jpg">
                      <h1> Join</h1>
                  </div>
              </div>

            </div> 
      </div>
    </div>
</div> 
  </div>


<div class ="container">
<%= render 'layouts/carouselstats'%>
</div>

app/views/static_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Static Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= link_to 'Show', static_page %></td>
        <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
        <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>