config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :supports
  resources :locations
  resources :partners
  resources :events do
    collection do
      get "search"
    end
  end
  resources :abouts
  resources :static_pages

  root 'static_pages#home'

  get 'board', to: 'abouts#board' 

end

app/views/layouts/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>




  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
   
        <img src="https://download.unsplash.com/photo-1429152937938-07b5f2828cdd" class = "img-responsive" style="width:100%;height:650px;" alt="Chania">
          
          <!-- <iframe width="450px" height="290px" src="https://www.youtube.com/embed/YXVKy2vO9Xg?rel=0&playlist=YXVKy2vO9Xg&disablekb=1;controls=0&amp;showinfo=0&autoplay=1" frameborder="0" style="position:absolute;top:290px;"></iframe> -->
        
    </div>

    <div class="item">
      <img src="https://download.unsplash.com/photo-1434139240289-56c519f77cb0" class = "img-responsive" style="width:100%;height:650px;" alt="Chania">
    </div>

    <div class="item">
      <img src="https://download.unsplash.com/photo-1433959352364-9314c5b6eb0b" class = "img-responsive" style="width:100%;height:650px;" alt="Flower">
    </div>

    <div class="item">
      <img src="https://download.unsplash.com/photo-1433838552652-f9a46b332c40" class = "img-responsive" style="width:100%;height:650px;" alt="Flower">
    </div>
  </div>

  <!-- Left and right controls -->
  
</div>

app/views/layouts/_carouselstats.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>




  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">

        <img src="https://download.unsplash.com/photo-1433650552684-d4004a945d6c" class = "img-responsive" style="width:100%;height:450px;" alt="Chania">
          
          <!-- <iframe width="450px" height="290px" src="https://www.youtube.com/embed/YXVKy2vO9Xg?rel=0&playlist=YXVKy2vO9Xg&disablekb=1;controls=0&amp;showinfo=0&autoplay=1" frameborder="0" style="position:absolute;top:290px;"></iframe> -->
        
    </div>

    <div class="item">
      <img src="https://download.unsplash.com/photo-1433256392503-913cee5877e3" class = "img-responsive" style="width:100%;height:450px;" alt="Chania">
    </div>

    <div class="item">
      <img src="https://download.unsplash.com/photo-1434145175661-472d90344c15" class = "img-responsive" style="width:100%;height:450px;" alt="Flower">
    </div>

    <div class="item">
      <img src="https://download.unsplash.com/photo-1433840496881-cbd845929862" class = "img-responsive" style="width:100%;height:450px;" alt="Flower">
    </div>
  </div>

  <!-- Left and right controls -->
  
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
 <%= render 'layouts/search' %>

    <!-- TOP NAVBAR -->
 
   
  


  <div class="row">
      <!-- MAIN NAVBAR -->
            <div class="container-fluid" style= "background-color:white;height:95px;">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header" style = "color:white;">
            <button type="button" class="navbar-toggle" data-toggle="collapse" 
             data-target="#myNavbar">
             <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>                        
            </button>

            <a class="navbar-brand" href="#"><img src = "http://i304.photobucket.com/albums/nn184/boysandgirlsclubsofthesouthbay/bgcsblogo.jpg_zps8tg0dxkd.png"  style = "height:80px;width:200px;"></a>
          </div>





          <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="myNavbar" style = "color:white;">
          <div class ="col-md-8 col-md-offset-0" style = "margin-top:25px;"> 
            <ul class="nav navbar-nav navbar-right" style="font-family:'Raleway', Helvetica, Arial, Lucida, sans-serif; font-size:15px;color:blue;background-color:white;">
              <!-- make dropdown collapse white. -->
              <li role="presentation"><%= link_to "Home", root_path %></li>
              <li role="presentation"><%= link_to "About", abouts_path %></li>
         
              <li role="presentation"><%= link_to "Events", events_path %></li>
              <li role="presentation"><%= link_to "Partners", partners_path %></a></li>
              <li role="presentation"><%= link_to "Locations", locations_path %></li>
              <li role="presentation"><%= link_to "Support - Coming Soon!", supports_path%></li>
              </li>
            </ul>
          </div>

          </div><!-- /.navbar-collapse -->

        </div><!-- /.container-fluid -->
  </div>
</div>
</div>

app/views/layouts/_sample.html.erb
<nav class = "nav navbar navbar-default">
		<div class = "container">
			<div class = "navbar-header">
				<div class = "navbar-brand"> <%= link_to "Dumo", root_path %></div>
			</div>
			  <button type="button" class="navbar-toggle" data-toggle="collapse" 
		         data-target="#myNavbar">
		         <span class="sr-only">Toggle navigation</span>
		         <span class="icon-bar"></span>
		         <span class="icon-bar"></span>
		         <span class="icon-bar"></span>
		      </button>


					<div class="collapse navbar-collapse" id="myNavbar">
						<ul class = "nav navbar-nav navbar-right navtitle">
              			<li role="presentation"><%= link_to "Home", root_path %></li>
							              <li role="presentation"><%= link_to "Home", root_path %></li>
              <li role="presentation"><%= link_to "Home", root_path %></li>
              <li role="presentation"><%= link_to "Home", root_path %></li>
              <li role="presentation"><%= link_to "Home", root_path %></li>

								
						</ul>
					


					<!--  SEARCH for Memes -->
				

					<!-- <form class  = "navbar-form navbar right" role = "search">
							<div class = "form-group">
								<input type = "text" class = "form-control" placeholder = "Search">
							</div>
						<button type = "submit" class = "btn btn-default"> Search </button>
					</form> -->
			</div>	


	</div>
</div>
</div>
</nav>

app/views/layouts/_search.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class = "row">
     <div class="container-fluid" style="background-color:#087db3">
            <!-- Brand and toggle get grouped for better mobile display -->
                

                <!-- FACEBOOK icon/link -->
                <a href = "https://www.facebook.com/pages/Boys-Girls-Clubs-of-The-South-Bay/155491257802264" target="_blank">
                  <img src = "http://i304.photobucket.com/albums/nn184/boysandgirlsclubsofthesouthbay/facebook_zpsa8bnwm3v.png" style ="float: right;margin-top:5px;">

                  <!-- ../../assets/facebook.png -->
                </a>

                <!-- TWITTER icon/link -->
                <a href = "https://twitter.com/bgcsouthbay" target="_blank">
                  <img src = "http://i304.photobucket.com/albums/nn184/boysandgirlsclubsofthesouthbay/twitter_zpseyvukskg.png" style ="float: right;margin-top:5px;">
                </a>

            <div class="col-lg-9" style = "float:left;">

            <!-- Search Events -->
              
         <form class="navbar-form pull-left" role="search">
            <div class="input-group">
               <input type="text" class="form-control" placeholder="Search">
               <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
               </div>
            </div>
         </form>





         <!-- Contact Info -->
            <!-- <a href="#contact">
              <h2 style="margin-top:5px;color:white;"> Contact </h2>
            </a> -->

         </div><!-- /.navbar-collapse -->
    </div>  
    
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boys and Girls Clubs of the South Bay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>

</head>
<body>

	
	<%= render 'layouts/navbar' %>

<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

<hr>
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Boys and Girls Clubs of the South Bay</p>
    </div>
  </div>
</footer>


</body>
</html>